swagger: '2.0'
info:
  title: DATAFARM TEST XSS
  description: This is a test API for demonstration purposes.
  version: 1.0.0
servers:
  - url: 
paths:
  /fetchData:
    get:
      summary: Fetches data from the test API
      operationId: getData
      parameters:
        - name: id
          in: query
          required: true
          description: The ID of the data to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "123"
                  name:
                    type: string
                    example: "Sample Data"
        '404':
          description: Data not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Data not found"
